sudo: false
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
jdk: oraclejdk8
before_install:
  - 'wget https://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz'
  - 'tar xf zookeeper-3.4.6.tar.gz'
  - 'mv zookeeper-3.4.6/conf/zoo_sample.cfg zookeeper-3.4.6/conf/zoo.cfg'
  - './zookeeper-3.4.6/bin/zkServer.sh start'
  - echo $JAVA_HOME
  - java -version
  - 'wget https://github.com/alibaba/nacos/releases/download/0.5.0/nacos-server-0.5.0.tar.gz'
  - 'wget https://github.com/gxcsoccer/PDisk/releases/download/1.0.0/startup.sh'
  - 'tar xf nacos-server-0.5.0.tar.gz'
  - 'mv ./startup.sh ./nacos/bin/startup.sh'
  - 'chmod 755 ./nacos/bin/startup.sh'
  - 'nohup ./nacos/bin/startup.sh -m standalone 2>&1 &'
  - 'sleep 30'
  - 'curl "127.0.0.1:8848/nacos/v1/ns/api/hello"'
install:
  - npm i
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
